### ISSUE TITLE
Can't refresh the list of MIDI devices on Mac OS X

### ISSUE THREAD

**Issue by MattPutnam** [MattPutnam/Cadenza#2]
The Mac OS X Java implementation has a bug that prevents refreshing the list of MIDI devices.  Research ways to get around this.

**Comment by Yona-Appletree** [comment]
I recently ran into the same problem, and there is now a library that correctly supports hot-plugging MIDI devices in Java on macOS: https://github.com/DerekCook/CoreMidi4J
